name: CI

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      REGISTRY: ghcr.io
      ORG: ${{ github.repository_owner }}

    steps:
      # Checkout codice
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java + cache Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Build Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Variabili dinamiche
      - name: Set up variables
        run: |
          APP_NAME=$(basename $GITHUB_REPOSITORY)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=$(date +%Y%m%d%H%M%S)

          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.ORG }}/$APP_NAME
          IMAGE_TAG=$IMAGE_NAME:$VERSION
          IMAGE_LATEST=$IMAGE_NAME:latest

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV

      # Login GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image (usa il jar gi√† creato)
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_TAG -t $IMAGE_LATEST .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_TAG
          docker push $IMAGE_LATEST